import React from "react";
import './App.css';

const Standings = () => {
    return (
        <div>
        <table>
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Team</th>
                    <th>GP</th>
                    <th>W</th>
                    <th>L</th>
                    <th>D</th>
                    <th>GF</th>
                    <th>GA</th>
                    <th>GD</th>
                    <th>PTS</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Jassim</td>
                    <td>6</td>
                    <td>5</td>
                    <td>0</td>
                    <td>1</td>
                    <td>19</td>
                    <td>7</td>
                    <td>12</td>
                    <td>16</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Shaker</td>
                    <td>6</td>
                    <td>5</td>
                    <td>1</td>
                    <td>0</td>
                    <td>26</td>
                    <td>11</td>
                    <td>15</td>
                    <td>15</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Mustafa</td>
                    <td>6</td>
                    <td>4</td>
                    <td>1</td>
                    <td>1</td>
                    <td>17</td>
                    <td>7</td>
                    <td>10</td>
                    <td>13</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Mahmoud</td>
                    <td>6</td>
                    <td>2</td>
                    <td>3</td>
                    <td>1</td>
                    <td>15</td>
                    <td>17</td>
                    <td>-2</td>
                    <td>7</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Sami</td>
                    <td>6</td>
                    <td>2</td>
                    <td>3</td>
                    <td>1</td>
                    <td>11</td>
                    <td>13</td>
                    <td>-2</td>
                    <td>7</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>Abu-Shanab</td>
                    <td>6</td>
                    <td>2</td>
                    <td>3</td>
                    <td>1</td>
                    <td>15</td>
                    <td>19</td>
                    <td>-4</td>
                    <td>7</td>
                </tr>
                <tr>
                    <td>7</td>
                    <td>Adil</td>
                    <td>6</td>
                    <td>1</td>
                    <td>5</td>
                    <td>0</td>
                    <td>6</td>
                    <td>19</td>
                    <td>-13</td>
                    <td>3</td>
                </tr>
                <tr>
                    <td>8</td>
                    <td>Rifai</td>
                    <td>6</td>
                    <td>0</td>
                    <td>5</td>
                    <td>1</td>
                    <td>10</td>
                    <td>26</td>
                    <td>-16</td>
                    <td>1</td>
                </tr>
            </tbody>
        </table>
            <div className="golden-boot-container">
        <h1 className="golden-boot-title">Golden Boot</h1>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Rank</th>
                        <th>Player</th>
                        <th>Team</th>
                        <th>Goals</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>Basim</td>
                        <td>Mustafa</td>
                        <td>17</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Ahmed</td>
                        <td>Jassim</td>
                        <td>10</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>Osama</td>
                        <td>Mustafa</td>
                        <td>8</td>
                    </tr>
                </tbody>
            </table>

        </div>
     );
}

export default Standings;
